# Generated by Django 6.1 on 2026-08-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='church_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='День, коли відзначається подія', verbose_name='Дата')),
                ('time', models.TimeField(blank=True, help_text='Час проведення події', null=True, verbose_name='Час')),
                ('title', models.CharField(help_text="Наприклад: 'Новий рік', 'День народження' тощо", max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, help_text="Детальніший опис події (необов'язково)", verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['date', 'time'],
            },
        ),
    ]
