# Generated by Django 6.0.4 on 2026-08-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TozymChurch_APP', '0002_church_schedule_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.AddField(
            model_name='church_schedule',
            name='holiday',
            field=models.CharField(blank=True, choices=[('', 'Без свята'), ('christmas', 'Різдво Христове'), ('epiphany', 'Богоявлення'), ('annunciation', 'Благовіщення'), ('palm_sunday', 'Вербна неділя'), ('easter', 'Великдень'), ('ascension', 'Вознесіння Господнє'), ('pentecost', "П'ятидесятниця"), ('transfiguration', 'Преображення Господнє'), ('dormition', 'Успіння Богородиці'), ('michaelmas', 'Собор Архангела Михаїла')], max_length=32, verbose_name='Свято'),
        ),
        migrations.AddField(
            model_name='church_schedule',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота'), (6, 'Неділя')], null=True, verbose_name='День тижня'),
        ),
        migrations.AlterField(
            model_name='church_schedule',
            name='title',
            field=models.CharField(blank=True, help_text="Наприклад: 'Новий рік', 'День народження' тощо", max_length=255, verbose_name='Назва'),
        ),
    ]
