# Generated by Django 6.0.4 on 2026-08-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TozymChurch_APP', '0003_product_church_schedule_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church_schedule',
            name='service_type',
            field=models.CharField(blank=True, choices=[('', 'Виберіть богослужіння'), ('divine_liturgy', 'Божественна літургія'), ('moleben_akathist', 'Молебень з акафістом'), ('moleben', 'Молебень'), ('vespers', 'Вечірня'), ('matins', 'Утреня'), ('confession', 'Сповідь'), ('panikhida', 'Панахида'), ('prayer_service', 'Молитовне правило'), ('parish_meeting', 'Парафіяльна зустріч')], max_length=32, verbose_name='Богослужіння'),
        ),
    ]
