# Generated by Django 6.0.4 on 2026-08-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TozymChurch_APP', '0004_church_schedule_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church_schedule',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='church_schedule',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='church_schedule',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='church_schedule',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='church_schedule',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='church_schedule',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='church_schedule',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='church_schedule',
            name='title_ru',
        ),
    ]
